config/routes.rb
Rails.application.routes.draw do
  
  resources :charges
  resources :pages, only: [:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tags, only: [:show]
  resources :categories, only: [:show]
  resources :products, only: [:index, :show]
  get 'cart' => 'products#cart', as: 'cart'
  post 'cart/:id' => 'products#add_to_cart', as: 'add_to_cart'
  post 'cart_delete/:id' => 'products#delete_from_cart', as: 'delete_from_cart'
  get 'cart_clear' => 'products#clear_cart', as: 'clear_cart'
  
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, :title, :price, presence: true
  validates :price, numericality: true
  belongs_to :tag
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    add_breadcrumb 'home', '/'

    @product = (Product.where('name LIKE ?', "%#{params[:term]}%") if params[:term])

    @fearured_product1 = Product.where('category_id = 1').sample
    @fearured_product2 = Product.where('category_id = 2').sample
    @fearured_product3 = Product.where('category_id = 3').sample
    @product_searched = Product.where('title LIKE ? AND category_id = ?', "%#{params[:term]}%", params[:cat_id])
    @idsearched = params[:cat_id]
  
    @test
  end

  def show
    @product = Product.find(params[:id])
    prod_name = @product.title
    prod_cat = @product.category.name
    catid = @product.category.id
    cat_path = '/categories/' + catid.to_s
    @item_path = '/products/' + params[:id]
    add_breadcrumb 'Home', root_path
    add_breadcrumb prod_cat, cat_path
    add_breadcrumb prod_name, @item_path
  end

  def cart

    @total_price = 0
    @prodcts_in_cart = Array.new()
    @quantity_per_product = Array.new()
    @prodcts_in_cart = session[:prodcts_in_cart] || @prodcts_in_cart
    @quantity_per_product = session[:quantity_per_product] || @quantity_per_product
    @total_price = session[:total_cart] || @total_price
    @products_obj = Product.find(@prodcts_in_cart)
    @count = @prodcts_in_cart.count


  end

  def add_to_cart
    prams = params[:id].to_i
    @prodcts_in_cart = Array.new()
    @quantity_per_product = Array.new()
    @prodcts_in_cart = session[:prodcts_in_cart] || @prodcts_in_cart
    @quantity_per_product = session[:quantity_per_product] || @quantity_per_product

    if @prodcts_in_cart.include?(prams)
      prod_index = @prodcts_in_cart.index(prams)
      @quantity_per_product[prod_index] +=1
    else
      @prodcts_in_cart << prams
      @quantity_per_product << 1
    end
    session[:prodcts_in_cart] = nil
    session[:quantity_per_product] = nil
    session[:prodcts_in_cart] =  @prodcts_in_cart
    session[:quantity_per_product] = @quantity_per_product
    update_total()
    redirect_to "/cart"
  end

  def delete_from_cart
    prasm = params[:id].to_i
    @prodcts_in_cart = Array.new()
    @quantity_per_product = Array.new()
    @prodcts_in_cart = session[:prodcts_in_cart] || @prodcts_in_cart
    @quantity_per_product = session[:quantity_per_product] || @quantity_per_product
    prod_index = @prodcts_in_cart.index(prasm)
    @quantity_per_product[prod_index] -= 1

    if @quantity_per_product[prod_index] <= 0
      @quantity_per_product.delete_at(prod_index)
      @prodcts_in_cart.delete_at(prod_index)
    end
    session[:prodcts_in_cart] = nil
    session[:quantity_per_product] = nil
    session[:prodcts_in_cart] =  @prodcts_in_cart
    session[:quantity_per_product] = @quantity_per_product
    update_total()
    redirect_to "/cart"

  end

  def clear_cart
    session[:prodcts_in_cart] = nil
    session[:quantity_per_product] = nil
    update_total()
    redirect_to "/cart"
  end

  def update_total
    @total_price = 0
    @prodcts_in_cart = Array.new()
    @quantity_per_product = Array.new()
    @prodcts_in_cart = session[:prodcts_in_cart] || @prodcts_in_cart
    @quantity_per_product = session[:quantity_per_product] || @quantity_per_product

    (1..@prodcts_in_cart.length).each do |i| 
      @total_price += (Product.find(@prodcts_in_cart[i-1]).price)*(@quantity_per_product[i-1])
    end
    session[:total_cart] = @total_price
    
  
  end
  
  def product_params
    params.require(:product).permit(:term)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/cart.html.erb
<%= render "shared/nav", category: @category, tags: @tag, pages: @page%>
<main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row mb-2">
                    <div class="col-md-12">  
                       <h2> Cart </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class= "container justify-content-between">
        <br/>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Product image</th>
                <th scope="col">Product Title</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
            <% (1..@prodcts_in_cart.length).each do |i|  %>
                <tr>
                    <td><%= image_tag(@products_obj[i-1].image.url, class:"card-img-search") %></td>
                    <td><%= @products_obj[i-1].title %></td>
                    <td><%= link_to '-', delete_from_cart_path(@products_obj[i-1]), method: :post %> <%= @quantity_per_product[i-1] %><%= link_to '+', add_to_cart_path(@products_obj[i-1]), method: :post %></td>
                    <td><%= (@products_obj[i-1].price)*(@quantity_per_product[i-1])%></td>
                </tr>
           <% end %>
                <tr>
                    <td>TOTAL</td>
                    <td></td>
                    <td><%= link_to 'CLEAR CART', clear_cart_path %> </span></td>
                    <td><%= @total_price %></td>
                </tr>
                 <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="td_check_out"><span class="check_out"><%= link_to 'CHECK OUT', 'charges/new'%></span></td>
                </tr>
  </tbody>
</table>
 </div>

 

app/views/products/index.html.erb
 <%= render "shared/nav", category: @category, tags: @tag, pages: @page%>

 

 <main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row mb-2">
                    <div class="col-md-12">  
                       <h2> Feature  Products </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
<%# <s%= select_tag(:user_id, options_for_select([['Jemmy Legs', 1], ['Talos', 2]]))%> 
<div class= "container justify-content-between">
    <%= form_tag(products_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
    <%= select_tag(:cat_id, options_for_select([['Hats', 1], ['T-Shirts', 2], ['Hoodies', 3]]))%> 
    <%= hidden_field_tag 'isSearch', 'true' %>
    <%= submit_tag 'Search', name: nil %>
</div>

  
  <% if params[:term] != "" %>
  <div class= "container justify-content-between">
    <main role="main">
        <div class="album py-5 bg-light">
            <div class="row">
                <% @product_searched.each do |pdct| %>
                    <div class="col-md-2">
                        <div class="card mb-2 shadow-sm">
                            <%= image_tag(pdct.image.url, class:"card-img-search") %>
                            <div class="card-body">
                                <p class="card-text"><%= link_to pdct.title, pdct %></p>
                                <div class="d-flex justify-content-between align-items-center"> </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </main> 
     </div>
  <% end %>
  

<% end %>
 <main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <%= image_tag(@fearured_product1.image.url, class:"card-img-top") %>
                        <div class="card-body">
                            <p class="card-text"><%= link_to @fearured_product1.title, @fearured_product1 %></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <%= image_tag(@fearured_product2.image.url, class:"card-img-top") %>
                        <div class="card-body">
                            <p class="card-text"><%= link_to @fearured_product2.title, @fearured_product2 %></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <%= image_tag(@fearured_product3.image.url, class:"card-img-top") %>
                        <div class="card-body">
                            <p class="card-text"><%= link_to @fearured_product3.title, @fearured_product3 %></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

app/views/products/show.html.erb
<%= render "shared/nav", category: @category, tags: @tag, pages: @page%>
 <main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row mb-2">
                    <div class="col-md-12">  
                        <h2> <%= @product.category.name %> </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
 <main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row mb-2">
                <div class="col-md-4">                    
                        <%= image_tag(@product.image.url) %>
                </div>
                <div class="col-md-8 prod_descrip">                    
                        <h2><%= @product.title %></h2>
                        <h3><%= @product.price %></h2>
                        <p><%= @product.description %></p>
                        <%= link_to 'ADD TO CART', add_to_cart_path(@product), method: :post %>
                </div>
            </div>
        </div>
    </div>
</main>