config/routes.rb
Rails.application.routes.draw do
  
  resources :charges
  resources :pages, only: [:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tags, only: [:show]
  resources :categories, only: [:show]
  resources :products, only: [:index, :show]
  get 'cart' => 'products#cart', as: 'cart'
  post 'cart/:id' => 'products#add_to_cart', as: 'add_to_cart'
  post 'cart_delete/:id' => 'products#delete_from_cart', as: 'delete_from_cart'
  get 'cart_clear' => 'products#clear_cart', as: 'clear_cart'
  
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
      # Amount in cents
      # @amount = 500
      @amount = ((session[:total_cart])*(100))
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount.to_i,
        :description => 'Rails Stripe customer',
        :currency    => 'CAD'
      )
      record_purchase()
      session[:charge] = charge
      session[:status] = charge.paid
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  def record_purchase
    customer = User.first
    prodcts_in_cart = Array.new()
    quantity_per_product = Array.new()
    prodcts_in_cart = session[:prodcts_in_cart] || prodcts_in_cart
    quantity_per_product = session[:quantity_per_product] || quantity_per_product
    statusId = 2

    if (session[:status])
      statusId=1
    end
    newOrder = Order.new(:user_id => customer.id,
      :status_id => statusId)
      newOrder.save!

    newOrderId = Order.last.id

    (1..prodcts_in_cart.length).each do |i| 
      prodPrice = Product.find(prodcts_in_cart[i-1]).price
      newPurchase = LineItem.new(:quantity => quantity_per_product[i-1],
        :unitPrice => prodPrice, 
        :GST => customer.province.GST,
        :PST => customer.province.PST,
        :HST => customer.province.HST,
        :product_id => prodcts_in_cart[i-1],
        :order_id => newOrderId)
        newPurchase.save!
    end
      
      session[:prodcts_in_cart] = nil
      session[:quantity_per_product] = nil
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<%= render "shared/nav", category: @category, tags: @tag, pages: @page%>
<main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row mb-2">
                    <div class="col-md-12">  
                       <h2> THANK YOU!! </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class= "container justify-content-between">
        <h2>Thanks, you paid <strong>$<%= (session[:total_cart]).to_f %></strong>!</h2> 
    </div>

app/views/charges/new.html.erb
<%= render "shared/nav", category: @category, tags: @tag, pages: @page%>
<main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row mb-2">
                    <div class="col-md-12">  
                       <h2> Check Out </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class= "container justify-content-between">
        <%= form_tag charges_path do %>
        <article>
            <% if flash[:error].present? %>
            <div id="error_explanation">
                <p><%= flash[:error] %></p>
            </div>
            <% end %>
            <label class="amount">
            <h2><span>Amount: $<%= session[:total_cart] %></span></h2>
            </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="A month's subscription"
                data-amount= "<%= ((session[:total_cart])*(100)) %>"
                data-locale="auto"></script>
        <% end %>
        </div>